### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by vanestorming** [barbanet/magento2-language-es_ar#1]
Hi, I'm having this issue when I try to install the package >

`c:\xampp\htdocs\magento210
λ composer require barbanet/magento2-language-es_ar
Using version ^0.3.0 for barbanet/magento2-language-es_ar
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for barbanet/magento2-language-es_ar ^0.3.0 -> satisfiable by barbanet/magento2-language-es_ar[0.3.0].
    - Conclusion: remove magento/framework 100.1.0
    - Conclusion: don't install magento/framework 100.1.0
    - barbanet/magento2-language-es_ar 0.3.0 requires magento/framework 100.0.\* -> satisfiable by magento/framework[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9].
    - Can only install one of: magento/framework[100.1.0, 100.0.2].
    - Can only install one of: magento/framework[100.1.0, 100.0.3].
    - Can only install one of: magento/framework[100.1.0, 100.0.4].
    - Can only install one of: magento/framework[100.1.0, 100.0.5].
    - Can only install one of: magento/framework[100.1.0, 100.0.6].
    - Can only install one of: magento/framework[100.1.0, 100.0.7].
    - Can only install one of: magento/framework[100.1.0, 100.0.8].
    - Can only install one of: magento/framework[100.1.0, 100.0.9].
    - Installation request for magento/framework (locked at 100.1.0) -> satisfiable by magento/framework[100.1.0].

Installation failed, reverting ./composer.json to its original content.`

Do you have any idea about how can I fix this problem?

Thanks in advance!

**Comment by barbanet** [comment]
Which version of Magento are you using? (Maybe 2.1?)

**Comment by vanestorming** [comment]
Yes, 2.1

**Comment by barbanet** [comment]
Sorry, too many notifications on Github. I've missed this one.
The problem is the compsoer.json file and the Magento's modules requirmetns versions.
I'll fix this in the next release (next week).
